version: '3'
services:
  api:
    build: ./api
    environment:
      - DB_USER=nextpex
      - DB_PASS=nextpex
      - DB_ADDR=db:3306
      - DB_NAME=nextpex
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      - MARIADB_USER=nextpex
      - MARIADB_PASSWORD=nextpex
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=nextpex
    ports:
      - "3600:3306"
