version: '3'
services:
  # db:
  #   image: mariadb:latest
  #   environment:
  #     - MARIADB_USER=nextpex
  #     - MARIADB_PASSWORD=nextpex
  #     - MARIADB_ROOT_PASSWORD=nextpex
  #     - MARIADB_DATABASE=nextpex
  #   ports:
  #     - "3600:3306"
  #   volumes:
  #     - "dbdata:/var/lib/mysql"
  #     - ./initdb.d:/docker-entrypoint-initdb.d
  #   restart: always

  bot:
    build: ./botv2
    env_file:
      - bot.env
    depends_on:
      - api
    profiles:
      - bot
    restart: always
  
  api:
    build: ./fastestserver
    ports:
      - "3601:9000"
    restart: always
    volumes:
      - ./data:/usr/src/app/data

  watcher:
    container_name: nextpex-watcher
    env_file:
      - watcher/.env
    build:
      context: watcher
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./watcher:/usr/src/app
      - ./data:/data
    ports:
      - "8088:1323"
volumes:
  dbdata:
