version: '3'
services:
  api:
    build: ./api
    environment:
      - DB_USER=nextpex
      - DB_PASS=nextpex
      - DB_ADDR=db:3306
      - DB_NAME=nextpex
    ports:
      - "3601:1323"
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      - MARIADB_USER=nextpex
      - MARIADB_PASSWORD=nextpex
      - MARIADB_ROOT_PASSWORD=nextpex
      - MARIADB_DATABASE=nextpex
    ports:
      - "3600:3306"
    volumes:
      - "dbdata:/var/lib/mysql"
  bot:
    build: ./bot
    env_file:
      - bot.env
    depends_on:
      - api
    profiles:
      - bot
  web:
    build: ./front
    ports:
      - "3602:80"
volumes:
  dbdata:
