version: '3'
services:
  # db:
  #   image: mariadb:latest
  #   environment:
  #     - MARIADB_USER=nextpex
  #     - MARIADB_PASSWORD=nextpex
  #     - MARIADB_ROOT_PASSWORD=nextpex
  #     - MARIADB_DATABASE=nextpex
  #   ports:
  #     - "3600:3306"
  #   volumes:
  #     - "dbdata:/var/lib/mysql"
  #     - ./initdb.d:/docker-entrypoint-initdb.d
  #   restart: always

  frontend:
    build: ./nextpex-frontend
    restart: unless-stopped
    ports:
      - "3600:80"
    depends_on:
      - api
    profiles:
      - frontend

  frontend-v2:
    build: ./frontend-v2
    restart: unless-stopped
    ports:
      - "3600:80"
    depends_on:
      - api
    profiles:
      - frontend-v2

  bot:
    build: ./botv2
    env_file:
      - botv2/.env
    depends_on:
      - api
    profiles:
      - bot
    restart: unless-stopped

  db:
    container_name: nextpex-db
    image: "postgres:latest"
    profiles:
      - devdb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=nextpex
      - POSTGRES_PASSWORD=nextpex
      - POSTGRES_DB=nextpex
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    container_name: nextpex-api
    build: ./fastestserver
    ports:
      - "3601:9000"
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - fastestserver/.env

  watcher:
    container_name: nextpex-watcher
    env_file:
      - watcher/.env
    build:
      context: watcher
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./watcher:/usr/src/app
      - ./data:/data
    ports:
      - "8088:1323"
volumes:
  redisdata:
  dbdata:
