# Generated by Django 3.2.9 on 2021-12-07 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rank', models.IntegerField()),
                ('new_rank', models.IntegerField()),
                ('rank_type', models.CharField(choices=[('trio', 'Trio'), ('arena', 'Arena')], max_length=10)),
                ('time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.player')),
            ],
        ),
        migrations.CreateModel(
            name='LevelUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_level', models.IntegerField()),
                ('new_level', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.player')),
            ],
        ),
        migrations.CreateModel(
            name='InGameName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_game_name', models.CharField(max_length=64)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.player')),
            ],
        ),
    ]
