# Generated by Django 3.2.9 on 2022-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_apexabilitycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankupdate',
            name='new_rank_name',
            field=models.CharField(default='bronze', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankupdate',
            name='old_rank_name',
            field=models.CharField(default='bronze', max_length=20),
            preserve_default=False,
        ),
    ]
