# Generated by Django 4.0.4 on 2022-05-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_userlink_pendinguserlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='apexabilitycheck',
            name='game',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='web.game'),
        ),
        migrations.AddIndex(
            model_name='apexabilitycheck',
            index=models.Index(
                fields=['game', '-time'], name='check_game_time_desc'),
        ),
    ]
