CREATE TABLE IF NOT EXISTS User(
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS InGameName(
    user_id INTEGER NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    game_name VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS Game(
    name VARCHAR(100) NOT NULL PRIMARY KEY,
);

CREATE TABLE IF NOT EXISTS LevelUpdate(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    old_level INTEGER,
    new_level INTEGER NOT NULL,
    timeat TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS RankUpdate(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    old_rank INTEGER,
    old_rank_name VARCHAR(20),
    new_rank INTEGER NOT NULL,make
    new_rank_name VARCHAR(20) NOT NULL,
    timeat TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PlayingTime(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    game_name VARCHAR(64) REFERENCES Game(name) ON DELETE SET NULL,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PendingPlay(
    user_id INTEGER NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    game_name VARCHAR(64) NOT NULL REFERENCES Game(name) ON DELETE CASCADE,
    started_at TIMESTAMP NOT NULL,
    UNIQUE (user_id)
);
